name: CD Maven (Build + Acceptance + Deploy Simulation)

on:
  push:
    branches: [ main ]  # Despliegue solo cuando se hace push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        working-directory: ./demo-app
        run: mvn -B test

      - name: Package application (build JAR)
        working-directory: ./demo-app
        run: mvn -B package

      - name: Run acceptance tests
        working-directory: ./demo-app
        run: mvn -B verify -Pacceptance-tests

      - name: Upload JAR artifact
        if: success()   # Solo si todo lo anterior pas√≥ bien
        uses: actions/upload-artifact@v4
        with:
          name: demo-app-jar
          path: demo-app/target/*.jar